services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - SERVER_PORT=8080
      - SELENIUM_REMOTE_URL=http://selenium:4444
      - ENV=TEST
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./src:/app/src
    depends_on:
      - selenium
