version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_TAG: "Latest"
    IMAGE_REPO_NAME: "sb_app"

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.9.0/packer_1.9.0_linux_amd64.zip && unzip packer.zip -d ./packer
  pre_build:
    on-failure: ABORT
    commands:
      - echo Running tests...
      - npm run test
  build:
    on-failure: ABORT
    commands:
      - echo Init packer
      - ./packer/packer init packer
      - echo Building AMI...
      - ./packer/packer build --force packer
      - echo Creating New Launch Template Version...
      - bash ./tools/update_launch_template.sh
  post_build:
    failure: ABORT
    commands:
      - echo Triggering ASG instance refresh...
      - bash ./tools/refresh_instances.sh
