version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_TAG: "Latest"
    IMAGE_REPO_NAME: "sb_app"

phases:
  install:
    on-failure: ABORT
    commands:
      # install packer
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install packer
  pre_build:
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - echo Running tests...
      - docker-compose run --use-aliases --rm --build backend
      - echo Shutting down test environment...
      - docker-compose down
  build:
    on-failure: ABORT
    commands:
      - echo Building AMI...
      - packer build --force packer
      - packer/launch_template.sh
  post_build:
    on-failure: ABORT
    commands:
      - echo Triggering ASG instance refresh...
      - packer/instance_refresh.sh
