version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_TAG: "Latest"
    IMAGE_REPO_NAME: "sb_app"

phases:
  install:
    on-failure: ABORT
    commands:
      # install packer
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.9.0/packer_1.9.0_linux_amd64.zip && unzip packer.zip -d ./packer
  pre_build:
    on-failure: ABORT
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - echo Running tests...
      - docker-compose build --no-cache
      - docker-compose run --use-aliases --rm backend
      - echo Shutting down test environment...
      - docker-compose down
  build:
    on-failure: ABORT
    commands:
      - echo Init packer
      - ./packer/packer init packer
      - echo Building AMI...
      - ./packer/packer build --force packer
      - BACKEND_AMI=`aws ec2 describe-images --filters "Name=name,Values=backend" --query 'Images[0].[ImageId]' --output text`
      - |
        aws ec2 create-launch-template-version \
        --launch-template-name backend \
        --launch-template-data "{"ImageId": "$BACKEND_AMI"}"
  post_build:
    failure: ABORT
    commands:
      - echo Triggering ASG instance refresh...
      - |
        aws ec2 start-instance-refresh \
        --auto-scaling-group-name backend \
        --desired-configuration '{ \
          "LaunchTemplate": { \
            "LaunchTemplateName": "backend", \
            "Version": "$Latest" \
          } \
        }' \
        --preferences '{ "AutoRollback": "true" }'
